

DATASET:
  # select your dataset (decomment only one of the following lines) 
  #type: EUROC_DATASET  
  #type: KITTI_DATASET
  type: TUM_DATASET
  # type: BONN_DATASET
  #type: REPLICA_DATASET
  # type: VIDEO_DATASET
  #type: FOLDER_DATASET
  #type: LIVE_DATASET  # Not recommended for current development stage


KITTI_DATASET:
  type: kitti
  sensor_type: stereo # Here, 'sensor_type' can be 'mono' or 'stereo'
  base_path: /home/luigi/Work/datasets/rgbd_datasets/kitti_color/dataset
  #
  # name: '06'
  # settings: settings/KITTI04-12.yaml # do not forget to correctly set the corresponding camera settings file 
  #
  name: '00'
  settings: dataset/KITTI00-02.yaml # do not forget to correctly set the corresponding camera settings file 
  #
  is_color: True # do you have the color images for the kitti dataset? (image2 and image3 folders)
  groundtruth_file: auto


TUM_DATASET:
  type: tum
  sensor_type: rgbd # Here, 'sensor_type' can be 'mono' or 'rgbd'
  # base_path: /home/luigi/Work/datasets/rgbd_datasets/tum
  base_path: /home/shashank/Documents/UniBonn/Sem4/ThesisPrep/pyslam/data/TUM # DATA FROM LEGION
  #
  #name: rgbd_dataset_freiburg3_long_office_household
  #settings: dataset/TUM3.yaml # do not forget to correctly set the corresponding camera settings file    
  #
  name: rgbd_dataset_freiburg1_desk
  settings: dataset/TUM1.yaml # do not forget to correctly set the corresponding camera settings file
  #
  # name: rgbd_dataset_freiburg3_walking_xyz  # do not use this for mono, there are some in-place rotations during exploratory phases
  # settings: dataset/TUM3.yaml # do not forget to set the corresponding camera settings file 
  #
  associations: associations.txt
  groundtruth_file: auto

  ##GS 
  pcd_downsample: 128
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

   ## 3DGS default parameters
  gs_opt_params:
    iterations: 30000
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.005
    lambda_dssim: 0.1
    densification_interval: 100
    opacity_reset_interval: 5000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002

  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False

BONN_DATASET:
  type: bonn
  sensor_type: rgbd # Here, 'sensor_type' can be 'mono' or 'rgbd'
  base_path: /home/shashank/Documents/UniBonn/Sem4/ThesisPrep/pyslam/data/TUM/ # DATA FROM LEGION
  # base_path: /cache/shashank/thesis/Datasets/data/TUM_RGBD #DATA FROM LAB

  #
  #name: rgbd_dataset_freiburg3_long_office_household
  #settings: dataset/TUM3.yaml # do not forget to correctly set the corresponding camera settings file    
  #
  #name: rgbd_dataset_freiburg1_xyz 
  #settings: dataset/TUM1.yaml # do not forget to correctly set the corresponding camera settings file
  #
  # name: rgbd_bonn_static_close_far # do not use this for mono, there are some in-place rotations during exploratory phases # DATA FROM LEGION
  name: rgbd_bonn_crowd ## DATA FROM LAB
  settings: dataset/rgbd_bonn.yaml # do not forget to set the corresponding camera settings file 
  #Parameters  
  associations: associations.txt
  groundtruth_file: auto

  ##GS 
  pcd_downsample: 128
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01


  ## 3DGS default parameters
  gs_opt_params:
    iterations: 30000
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002

  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False


VIDEO_DATASET:
  type: video
  sensor_type: mono   # Here, 'sensor_type' can be only 'mono' 
  #
  #base_path: ./data/videos/kitti00
  #settings: dataset/KITTI00-02.yaml
  #name: video.mp4
  #
  base_path: ./data/videos/kitti06
  settings: dataset/KITTI04-12.yaml
  name: video_color.mp4
  #
  #base_path: ./data/videos/webcam
  #settings: dataset/WEBCAM.yaml 
  #name: video.mp4
  #
  groundtruth_file: groundtruth.txt
  timestamps: times.txt # to be intended as the frame timestamps



